In [1]:
L1= [10,20,30,40,50]
L2 = [1,2,3,4,5]

In [2]:
L3 = L1+L2
print(L3)

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]


In [3]:
import numpy as np

In [4]:
array1= np.array([10,20,30,40,50])
array2 = np.arange(5)

In [5]:
array1

array([10, 20, 30, 40, 50])

In [6]:
array2

array([0, 1, 2, 3, 4])

In [7]:
array3 = array1+array2
array3

array([10, 21, 32, 43, 54])

In [8]:
sum(array1,array2)

array([150, 151, 152, 153, 154])

In [9]:
array4 = np.array([1,2,3,4])

In [10]:
array4+array1   
# we cannot add arrays with different dimensions, to add arrays the dimensions of both arrays have to be same

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [11]:
print(array4.shape)

(4,)


In [12]:
print(array1.shape)

(5,)


In [13]:
array = np.linspace(1,10,5)
array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
array*2

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [15]:
array**2

array([  1.    ,  10.5625,  30.25  ,  60.0625, 100.    ])

##### hstack and vstack

In [16]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

In [17]:
np.hstack((array1,array2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.vstack((array1,array2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
array1= np.arange(12).reshape(3,4)  ##3x4 matrix i.e., 3 rows and 4 columns
array1

In [ ]:
array2= np.arange(20).reshape(5,4)
array2

In [ ]:
array3= np.arange(12).reshape(4,3)  ## 4x3 matrix i.e,. 4 rows and 3 columns
array3

In [ ]:
np.vstack((array1,array2))

In [ ]:
np.vstack((array1,array3))   ### This will show an error as the dimensions of the column are not the same

In [ ]:
np.arange(12).reshape(2,6)  

In [ ]:
np.arange(12).reshape(6,2)

##### Index of the 100th Element

Consider an (11,12) shape array. 

What is the index (x,y) of the 100th element? 

Note: For counting the elements, go row-wise. For example, in the array:


[[1, 5, 9],
 [3, 0, 2]]
the 5th element would be '0'.

In [ ]:
array100 = np.arange(1,133).reshape(11,12)
array100

### Answer: 100 is present in 8th row and 3rd column. So (8,3). Note that indexing starts from 0 for both rows and coloumns

#### Reshaping an Array
Suppose you have an array 'p': 
[[1, 5],
 [3, 7],
 [4, 9]]
 
 What will be the output of the following code? np.reshape(p, -1)

Answer: 1-D Array

In [ ]:
p = np.array([[1, 5], [3, 7], [4, 9]])

In [ ]:
np.reshape(p,-1)

In [ ]:
help(np.reshape)

##### Reshaping an Array

Consider the array provided below: 

[[1, 2, 3, 4, 5]
 [6, 7, 8, 9, 10]
 [11, 12, 13, 14, 15]
 [16, 17, 18, 19, 20]]
 
Now, you are expected to generate the following array out of it:

[[1, 3]
 [5, 7]
 [9, 11]
 [13, 15]
 [17, 19]]
 
Which code will give you the correct output?


#### Answer

Step 1: Subset the array and apply the condition

Step 2: reshape the array into a 5x2 matrix

In [ ]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]])
a

In [ ]:
a[a%2!=0].reshape(5,2)

Reshaping an array
Suppose you have an array 'p'

[[1, 5],
 [3, 7],
 [4, 9]]
 
What will be the output of the following code?

np.reshape(p, (1, -1))
 

In [ ]:
p = np.array([[1, 5], [3, 7], [4, 9]])
p.shape

In [ ]:
p.ndim

In [ ]:
p1 = np.reshape(p,(1,-1))
p1

In [ ]:
p1.ndim

##### Stacking arrays

Description
Merge the three arrays provided to you to form a one 4x4 array.

[Hint: Check the function np.transpose() in the 'Manipulating Arrays' notebook provided.]



Input:

#### Array 1: 3*3

[[7, 13, 14]

[18, 10, 17]

[11, 12, 19]]



##### Array 2: 1-D array

[16, 6, 1]



#### Array 3: 1*4 array

[[5, 8, 4, 3]]



##### Output:

[[7 13 14 5]

[18 10 17 8]

[11 12 19 4]

[16 6 1 3]]

In [24]:
array1 = np.array([[7, 13, 14],[18, 10, 17],[11, 12, 19]])

In [25]:
array2 = np.array([16, 6, 1])

In [26]:
array3= np.array([[5, 8, 4, 3]])

In [27]:
array1.shape

(3, 3)

In [28]:
array2.shape

(3,)

In [29]:
array3.shape

(1, 4)

In [30]:
new_array = np.vstack((array1,array2))
new_array

array([[ 7, 13, 14],
       [18, 10, 17],
       [11, 12, 19],
       [16,  6,  1]])

In [31]:
new_array.shape

(4, 3)

In [32]:
temp_array = np.transpose(new_array)
temp_array

array([[ 7, 18, 11, 16],
       [13, 10, 12,  6],
       [14, 17, 19,  1]])

In [33]:
temp_array.shape

(3, 4)

In [34]:
final_array = np.vstack((temp_array,array3))
final_array

array([[ 7, 18, 11, 16],
       [13, 10, 12,  6],
       [14, 17, 19,  1],
       [ 5,  8,  4,  3]])

In [38]:
output = np.transpose(final_array)
output

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])

##### Numpy inbuilt functions

###### Raise all the elements in the output array to the power of 3

In [39]:
import numpy as np
np.power(output,3)

array([[ 343, 2197, 2744,  125],
       [5832, 1000, 4913,  512],
       [1331, 1728, 6859,   64],
       [4096,  216,    1,   27]], dtype=int32)

In [40]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
x = np.array([-1,1,-2,3,-5,7, -10])

In [44]:
np.absolute(x)

array([ 1,  1,  2,  3,  5,  7, 10])