In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [91]:
arr= np.ones(5,dtype= int)
arr

array([1, 1, 1, 1, 1])

In [92]:
arr.dtype

dtype('int32')

#### Create an  array of 5X3 ones

In [102]:
np.ones((5,3),dtype = int) 
# Note: Inside the paranthesis of np.ones(), the format is (row,columns). Hence we have 5 rows and 3 columns in output

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [100]:
np.ones((4,1),dtype = int).reshape(2,2)  

array([[1, 1],
       [1, 1]])

In [17]:
np.ones(9,dtype = int).reshape(3,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
import random
np.random.randint(5,size=10)

array([3, 1, 2, 2, 0, 4, 4, 4, 2, 0])

In [59]:
np.random.random(1)

array([0.44907855])

In [60]:
np.random.random(2)

array([0.36031559, 0.7470005 ])

In [83]:
np.random.random([3,4])

array([[0.19694807, 0.19527139, 0.35679963, 0.83116694],
       [0.97242677, 0.78071955, 0.98991906, 0.44190702],
       [0.75209301, 0.91797687, 0.80994272, 0.16603937]])

In [62]:
np.random.random(4)

array([0.43952489, 0.16354071, 0.65802246, 0.95630957])

#### Generate 100 random numbers between 0 and 1

In [63]:
np.random.random(100) 

array([0.48967834, 0.46153433, 0.48277469, 0.38476991, 0.16134423,
       0.12488566, 0.80333778, 0.71195843, 0.51178916, 0.56687637,
       0.15215829, 0.34765106, 0.05386023, 0.49379099, 0.86997034,
       0.43473028, 0.11002872, 0.39925532, 0.4591626 , 0.70730068,
       0.32379844, 0.46392133, 0.7632778 , 0.84031789, 0.46875266,
       0.16233638, 0.77757835, 0.36121876, 0.56957109, 0.17761509,
       0.4254481 , 0.41900756, 0.50077731, 0.30278567, 0.47690648,
       0.34269283, 0.56269026, 0.01210742, 0.51767001, 0.83255243,
       0.29211134, 0.23669247, 0.07525482, 0.98880108, 0.0267255 ,
       0.75684689, 0.8922291 , 0.12454821, 0.1003515 , 0.5117935 ,
       0.74817088, 0.51883881, 0.28639832, 0.27271632, 0.84092419,
       0.95504187, 0.52439383, 0.52352223, 0.89248585, 0.80827311,
       0.52433909, 0.83093096, 0.97906191, 0.08065212, 0.40769697,
       0.22252477, 0.5254295 , 0.16835173, 0.51802901, 0.34097385,
       0.8525347 , 0.613634  , 0.39213491, 0.60572787, 0.18197

#### Create an array of first 10 multiples of 5 using the 'arange' function.

In [65]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [107]:
np.arange(3,35,2)  #3 to 35 with a step of 2

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

#### Create an array of odd numbers between 1 and 100

In [104]:
odd = np.arange(1,101,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [79]:
len(odd)

50

#### Create an array of even numbers between 0 and 100

In [70]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [84]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

#### Array of length 20 equally spaced between 1 and 10

In [110]:
np.linspace(1,10,20)  # default data type is float

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [112]:
np.linspace(1,10,20,dtype = int)

array([ 1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
        9,  9, 10])

Create border array
Description
Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

Note: Make sure the array is of type int.

Example:

Input 1:

4

Output 1:

[[1 1 1 1]

[1 0 0 1]

[1 0 0 1]

[1 1 1 1]]

Input 2:

2

Output 2:

[[1 1] 

 [1 1]] 

In [119]:
n = int(input())

import numpy as np

# Create an 'n*n' array of all ones
border_array = np.ones((n,n),dtype = int)

# Fill the array with zeroes from second index (i.e. index 1) to second last index.

# Do this for both row indices and column indices
border_array[1:-1, 1:-1] = 0   #[row,column]
# Print the array created
print(border_array)

4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [137]:
n= int(input())
border = np.ones((n,n),dtype = int)
border[1:-1,1:-1] = 0
print(border)

6
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [140]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array set

In [142]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [143]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [146]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
np.eye(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [148]:
np.eye(4,dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])