In [ ]:
## Numpy vs Lists 


NumPy, which stands for ‘Numerical Python’, is a library meant for scientific calculations. The basic data structure of NumPy is an array.
A NumPy array is a collection of values stored together, similar to a list.

This video mentioned two different advantages that NumPy arrays have over lists. These include:

1. Ability to operate on individual elements in the array without using loops or list comprehension.
2. Speed of execution ... a NumPy array is faster than a list.

Creating NumPy Arrays There are two ways to create NumPy arrays, which are mentioned below.

1. By converting the existing lists or tuples to arrays using np.array 
2. By initialising fixed-length arrays using the NumPy functions. NumPy can have single and multi dimensional arrays to operate on.


The key advantage of using NumPy arrays over lists is that arrays allow you to operate over the entire data, unlike lists.
However, in terms of structure, NumPy arrays are extremely similar to lists. If you try to run the print() command over a NumPy array, then you will get the following output:

[element_1 element_2 element_3…]


The only difference between a NumPy array and a list is that the elements in the NumPy array are separated by a space instead of a comma.
Hence, this is an aesthetic feature that differentiates a list and a NumPy array.

Another feature of NumPy arrays is that they are homogeneous in nature.By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which could be an integer, float, string, etc.

In [2]:
#Let's define a list in python.
heights = [74, 75, 72, 72, 71]

In [3]:
# Print the heights.
heights

[74, 75, 72, 72, 71]

In [6]:
# Try to multiple heights with a scalar.
heights * 2.54

TypeError: can't multiply sequence by non-int of type 'float'

In [7]:
import numpy as np

In [9]:
# Deine a NumPy array
np_heights = np.array([74, 75, 72, 72, 71])

In [10]:
np_heights

array([74, 75, 72, 72, 71])

In [11]:
# Print the type of a NumPy array.
type(np_heights)

numpy.ndarray

In [12]:
# Multiple height (NumPy array) with a scalar.
np_heights * 2.54

array([187.96, 190.5 , 182.88, 182.88, 180.34])


#### NumPy comes with its own set of methods and operations

In [40]:
# Let's define two lists and perform '+' operation on that.
list_1 = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [41]:
# Let's define two NumPy array and perform '+' operation on that.
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
np1 + np2

array([5, 7, 9])

#### Working with N-D Arrays

In [45]:
np_heights

array([74, 75, 72, 72, 71])

In [46]:
type(np_heights)

numpy.ndarray